name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: macos-11
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4
      -
        name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção da imagem Docker
        run: echo "Executando o comando Docker Build"
      - name: Envio da imagem Docker
        run: "Executando o comando Docker push"  

  cd:
    runs-on: macos-11
    needs: [ci]
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o comando aws configure"
      - name: Configurar o kubectl
        run: echo "Executar o comando aws eks update-kubeconfig"
      - name: Deploy dos manifestos no Kubernetes
        run: echo "Executando o comando Kubectl apply"
